# version: '3.7'
# services:
#   postgresqldb:
#     image: postgres:15-alpine
#     restart: always
#     environment:
#       - POSTGRES_USER=username
#       - POSTGRES_PASSWORD=password
#     ports:
#       - '5433:5432'
#     volumes: 
#       - ./postgresql-init.sql:/docker-entrypoint-initdb.d/init.sql

#   springapp:
#     build: .
#     depends_on:
#       - postgresqldb
#     ports:
#       - '8081:8080'

version: '3'
services:
  oracle19c:
    build: .
    ports:
      - "1521:1521"
    shm_size: '4g'
